### ISSUE TITLE
Unable to merge GraphQL directive "sql"

### ISSUE THREAD

**Issue by chilarai** [taylrun/graphql-to-sql#2]
I am the example in [README](https://github.com/taylrun/graphql-to-sql/blob/master/README.md). But, when I run `node generate-sql.js`, I receive the following error

```
file:///Users/Tests/tt/node_modules/@graphql-tools/merge/esm/typedefs-mergers/directives.js:80
        throw new Error(`Unable to merge GraphQL directive "${node.name.value}". \nExisting directive:  \n\t${printedExistingNode} \nReceived directive: \n\t${printedNode}`);
              ^


Error: Unable to merge GraphQL directive "sql". 
Existing directive:  
	directive @sql(unicode: Boolean, constraints: String, auto: Boolean, default: String, index: Boolean, nullable: Boolean, primary: Boolean, type: String, unique: Boolean) on OBJECT | FIELD_DEFINITION 
Received directive: 
	directive @sql(unicode: Boolean, auto: Boolean, default: String, hide: Boolean, index: Boolean, nullable: Boolean, primary: Boolean, type: String, unique: Boolean, generated: String, constraints: String) on OBJECT | FIELD_DEFINITION
    at validateInputs (file:///Users/Tests/tt/node_modules/@graphql-tools/merge/esm/typedefs-mergers/directives.js:80:15)
    at mergeDirective (file:///Users/Tests/tt/node_modules/@graphql-tools/merge/esm/typedefs-mergers/directives.js:85:9)
    at mergeGraphQLNodes (file:///Users/Tests/tt/node_modules/@graphql-tools/merge/esm/typedefs-mergers/merge-nodes.js:56:49)
    at mergeGraphQLTypes (file:///Users/Tests/tt/node_modules/@graphql-tools/merge/esm/typedefs-mergers/merge-typedefs.js:67:30)
    at mergeTypeDefs (file:///Users/Tests/tt/node_modules/@graphql-tools/merge/esm/typedefs-mergers/merge-typedefs.js:10:22)
    at makeExecutableSchema (file:///Users/Tests/tt/node_modules/@graphql-tools/schema/esm/makeExecutableSchema.js:69:32)
    at generateSql (file:///Users/Tests/tt/node_modules/graphql-to-sql/lib/index.js:60:26)
    at file:///Users/Tests/tt/index.js:52:13
    at ModuleJob.run (node:internal/modules/esm/module_job:194:25)
```

**Node.js version**
v18.16.0

What could be wrong?

**Comment by taylrun** [comment]
Thanks. This was being caused because the appearance of the @sql in `typeDefs` was defined differently than the directive's definition in `index.ts`. Should be working now in 4.0.4.
